video:
  source: "C:/Users/kaust/OneDrive/Desktop/Learning/video_analytics_pipeline/Whatsapp Vid 2.mp4"
  width: 540
  height: 900

detector:
  model_path: "yolov8n.pt"
  confidence_threshold: 0.5
  classes: null

tracker:
  max_age: 40
  min_hits: 3
  iou_threshold: 0.3

scene_monitor:
  missing_object_frames: 15
  stability_frames: 5

visualization:
  show_fps: true
  show_boxes: true
  show_labels: true
  box_thickness: 2
  text_size: 0.5
  text_thickness: 2
  missing_color: [0, 0, 255]
  new_color: [0, 255, 0]
  normal_color: [255, 0, 0]
