video:
  source: "C:/Users/kaust/OneDrive/Desktop/Learning/Real Time ObjectDetection/video_analytics_pipeline/Whatsapp Vid 2.mp4" # 0 for webcam, can be a file path or RTSP URL
  # source: 0 # 0 for webcam, can be a file path or RTSP URL
  width: 540
  height: 900

detector:
  model_path: "yolov8n.pt"
  confidence_threshold: 0.5
  classes: null # null for all classes, or list of class IDs to detect

tracker:
  # max_age: 30
  max_age:
    40
    # maximum frames a track can be lost before deletion
  min_hits: 3
  # min_hits: 1
  # minimum hits to initialize a track
  iou_threshold: 0.3 # IOU threshold for track assignment

scene_monitor:
  missing_object_frames: 15
  # missing_object_frames: 20
  # frames before an object is considered missing
  stability_frames: 5 # frames before a new object is considered stable

visualization:
  show_fps: true
  show_boxes: true
  show_labels: true
  box_thickness: 2
  text_size: 0.5
  text_thickness: 2
  missing_color: [0, 0, 255] # BGR red for missing objects
  new_color: [0, 255, 0] # BGR green for new objects
  normal_color: [255, 0, 0] # BGR blue for normal objects
